changesetIgnorePatterns:
  - "**/*.spec.{js,ts,tsx}"
  - packages/docsite/**
  - packages/test-suite-*/**

enableInlineHunks: true

npmAuthToken: "${NPM_AUTH_TOKEN-emptytoken}"

packageExtensions:
  gatsby@*:
    dependencies:
      babel-plugin-styled-components: ^1.11.1
  react-frame-component@*:
    peerDependenciesMeta:
      react-dom: { optional: true }
  '@testing-library/react@*':
    peerDependenciesMeta:
      react-dom: { optional: true }

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
