const APIDocs: { [key: string]: any } = {
	OVERVIEW: require('../docs/00 Quick Start/Overview.md'),
	TUTORIAL: require('../docs/00 Quick Start/Tutorial.md'),
	TESTING: require('../docs/00 Quick Start/Testing.md'),
	FAQ: require('../docs/00 Quick Start/FAQ.md'),
	TROUBLESHOOTING: require('../docs/00 Quick Start/Troubleshooting.md'),
	DRAG_SOURCE: require('../docs/01 Top Level API/DragSource.md'),
	DRAG_SOURCE_MONITOR: require('../docs/03 Monitoring State/DragSourceMonitor.md'),
	DRAG_SOURCE_CONNECTOR: require('../docs/02 Connecting to DOM/DragSourceConnector.md'),
	DROP_TARGET: require('../docs/01 Top Level API/DropTarget.md'),
	DROP_TARGET_CONNECTOR: require('../docs/02 Connecting to DOM/DropTargetConnector.md'),
	DROP_TARGET_MONITOR: require('../docs/03 Monitoring State/DropTargetMonitor.md'),
	DRAG_DROP_CONTEXT: require('../docs/01 Top Level API/DragDropContext.md'),
	DRAG_DROP_CONTEXT_PROVIDER: require('../docs/01 Top Level API/DragDropContextProvider.md'),
	DRAG_LAYER: require('../docs/01 Top Level API/DragLayer.md'),
	DRAG_LAYER_MONITOR: require('../docs/03 Monitoring State/DragLayerMonitor.md'),
	HTML5_BACKEND: require('../docs/04 Backends/HTML5.md'),
	TEST_BACKEND: require('../docs/04 Backends/Test.md'),
}
export default APIDocs
