#!/bin/sh

# build examples
cd examples
../node_modules/.bin/webpack --config webpack.config.production.js
cd ..

# build minified standalone version in dist
./node_modules/.bin/webpack

# build ES5 modules in dist-modules
./node_modules/.bin/6to5 ./modules --out-dir dist-modules
