name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy-documentation:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: yarn install
      - run: 'yarn build:'
      - run: yarn build:docsite

      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.10.1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./packages/docsite/public
